name: re_walls
description: Street art UY.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 5.0.0
  carousel_slider: 3.0.0
  shared_preferences: 2.0.5
  http: 0.13.1
  cached_network_image: 3.0.0
  share: 2.0.1
  webview_flutter: 2.0.4
  image_downloader: 0.30.0
  font_awesome_flutter: 9.0.0
  permission_handler: 7.0.0
  fluttertoast: 8.0.6
  url_launcher: 6.0.3
  google_maps_flutter_web: ^0.4.0+3
  google_maps_flutter: ^2.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0
  
flutter:
  uses-material-design: true

  # assets:
  #  - assets/images/
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
